onboarding = false

[ui]
show_agent_labels_on_pane_borders = true

[theme]
name = "tokyo-night"
auto_switch = false

[ui.toast]
delivery = "herdr"

[keys]
clear_pane = "cmd+k"
prefix = "ctrl+a"

focus_pane_left = ["prefix+h", "ctrl+alt+h"]
focus_pane_down = ["prefix+j", "ctrl+alt+j"]
focus_pane_up = ["prefix+k", "ctrl+alt+k"]
focus_pane_right = ["prefix+l", "ctrl+alt+l"]
