return {}
-- return {
--   { "saghen/blink.cmp", enabled = false },
--   { "saghen/blink.compat", enabled = false },
--   { "rafamadriz/friendly-snippets", enabled = false },
-- }
-- print("blink_cmp.lua loaded!")
-- return {
--   "saghen/blink.cmp",
--   opts = {
--     snippets = {
--       placeholder = "", -- remove the ● placeholder
--     },
--   },
-- }
