return {}
-- return {
--   {
--     "neovim/nvim-lspconfig",
--     config = function()
--       vim.api.nvim_create_autocmd("LspAttach", {
--         callback = function(args)
--           local client = vim.lsp.get_client_by_id(args.data.client_id)
--           if client and client.name == "tsserver" then
--             client.server_capabilities.diagnosticProvider = nil
--           end
--         end,
--       })
--     end,
--   },
-- }
