return {}
-- return {
--   {
--     "nvim-telescope/telescope.nvim",
--     opts = {
--       defaults = {
--         hidden = true,
--       },
--       pickers = {
--         find_files = {
--           find_command = {
--             "fd",
--             "--type",
--             "f",
--             "--hidden",
--             "--exclude",
--             "node_modules",
--             "--exclude",
--             ".git",
--             "--color",
--             "never",
--             "--no-require-git",
--           },
--         },
--       },
--     },
--     keys = {
--       {
--         "<leader>ff",
--         function()
--           require("telescope.builtin").find_files()
--         end,
--         desc = "Find files (including hidden, excluding node_modules)",
--       },
--       {
--         "<Space><Space>",
--         function()
--           require("telescope.builtin").find_files()
--         end,
--         desc = "Find files (including hidden, excluding node_modules)",
--       },
--     },
--   },
-- }
