return {}
-- return {
--     {
--         "nvim-telescope/telescope.nvim",
--         opts = {
--             defaults = {
--                 hidden = true,
--             },
--         },
--         keys = {
--             {
--                 "<leader>ff",
--                 function()
--                     require("telescope.builtin").find_files({ hidden = true })
--                 end,
--                 desc = "Find files (including hidden)",
--             },
--             {
--                 "<leader>fh",
--                 function()
--                     require("telescope.builtin").find_files({ hidden = true })
--                 end,
--                 desc = "Find hidden files",
--             },
--         },
--     },
-- }
